### PR TITLE
Renderer fixes/simplications

### PR DESCRIPTION
**Pull request by pbiron**

### CODE REVIEW

**Comment by pbiron** [comment]
Important to note that the `<xhtml:link>` elements added to the sitemap will **not** be rendered by the XSLT core uses when a user opens `https://example.com/wp-sitemap-posts-page-1.xml`, etc. in a browser.  That could cause confusion among the users of this plugin (i.e., they may think that it is not adding those elements).

See https://github.com/GoogleChromeLabs/wp-sitemaps/pull/163 for a PR that I did for[ the sitemaps feature plugin](https://wordpress.org/plugins/core-sitemaps/) that would have allowed **some** extension elements to be rendered by core's XSLT...although it wouldn't have helped in this case, since it only rendered element content of such extension elements...and for this it would need to render the attributes of `<xhtml:link>` (further evidence that allowing core to provide hooks that would support **arbitrary** extension elements in the sitemap is a **hard** problem...which is one of the main reasons it was pulled before the feature plugin was merged into core).

**Comment by jsmoriss** [comment]
Thanks for the suggestions! I implemented your suggestions, but kept the recursive method to handle all tests in a single switch.

**Comment by pbiron** [comment]
> Thanks for the suggestions! I implemented your suggestions, but kept the recursive method to handle all tests in a single switch.

I will point out that your `add_items()` method allows the renderer to output invalid sitemaps.  You can easily see this by adding (e.g., in another plugin):

```
add_filter(
   'wp_sitemaps_posts_entry',
   function( $entry ) {
     // cause the generated sitemap to be invalid by adding the 'href' key directly in the entry.
     $entry['href'] = 'something';

    return $entry;
  }
);
```

which will result in a sitemap such as:

```
<urlset  xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>
  <url href='something'>
    <loc>https:/example.com</loc>
  </url>
</urlset>
```

Why?  Because `add_items()` doesn't check that the only place `href` and `hreflang` appear in the enties in `$url_list` passed to `get_sitemap_xml()` are as keys in the array that is the "child" of the `alternates` key.  And the way it's written, I think it would be hard (if not impossible) to check that the "context" in which the `href` and `hreflang` keys occur.  That "context checking" was handled in the changes in this PR.

Mind you, there was a bug in the PR as submitted :-) .  It should have been:

```
// Add each element as a child node to the <url> entry.
foreach ( $url_item as $name => $value ) {
	if ( 'loc' === $name ) {
		$url->addChild( $name, esc_url( $value ) );
	} elseif ( in_array( $name, array( 'lastmod', 'changefreq', 'priority' ), true ) ) {
		$url->addChild( $name, esc_xml( $value ) );
	} elseif ( 'alternates' === $name && ! empty( $value ) ) {
		foreach ( $value as $attributes ) {
			$xhtml_link = $url->addChild( 'link', null, 'http://www.w3.org/1999/xhtml' );
			$xhtml_link->addAttribute( 'rel', 'alternate' );

			foreach ( $attributes as $attr_name => $attr_value ) {
				if ( 'href' === $attr_name ) {
					$xhtml_link->addAttribute( $attr_name, esc_url( $attr_value ) );
				} elseif ( 'hreflang' === $attr_name ) {
					$xhtml_link->addAttribute( $attr_name, esc_attr( $attr_value ) );
				}
				// @todo pvb: allow other attributes on xhtml:link (e.g., @charset)?  I don't know if
				//       Google et. al accept any attributes other than @rel, @href, and @hreflang
				//       that are legal in XHTML...or only those 3.
			}
		}
	} else {
		_doing_it_wrong(...)
	}
}
```

**Comment by pbiron** [comment]
You probably also want to verify that both `href` and `hreflang` are supplied for each alternate (and call `_doing_it_wrong()` if not).  Neither is required by XHTML (nor HTML 5, for that matter), but I'm pretty sure search engines would barf (or just ignore the URL) if `xhtml:link/@href` were specified but `xhtml:link/@hreflang` weren't.

**Pull request closed without merging**
